2018-12-20 17:32:29,154 ERROR: Exception on /index [GET] [in d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Experiments\Python\SampleFlaskApplication\app\routes.py", line 32, in index
    return render_template('index.html', title='Home', posts=posts)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\index.html", line 17, in template
    {% end if%}
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 212, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'end'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-12-20 17:32:52,566 INFO: Microblog startup [in D:\Experiments\Python\SampleFlaskApplication\app\__init__.py:41]
2018-12-20 17:35:40,783 INFO: Microblog startup [in D:\Experiments\Python\SampleFlaskApplication\app\__init__.py:41]
2018-12-20 17:36:33,869 INFO: Microblog startup [in D:\Experiments\Python\SampleFlaskApplication\app\__init__.py:41]
2018-12-20 19:48:10,994 INFO: Microblog startup [in D:\Experiments\Python\SampleFlaskApplication\app\__init__.py:41]
2018-12-20 19:48:20,039 ERROR: Exception on /index [GET] [in d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Experiments\Python\SampleFlaskApplication\app\routes.py", line 36, in index
    return render_template('index.html', title='Explore', posts=posts, next_url=next_url, prev_url=prev_url)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\base.html", line 52, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2018-12-20 19:49:26,379 INFO: Microblog startup [in D:\Experiments\Python\SampleFlaskApplication\app\__init__.py:41]
